// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBncQgoBGNE6GBKa4m6rDtOTxDwbRyMDtA',
    appId: '1:624102922978:ios:e62f4ddce550611b55dcbb',
    messagingSenderId: '624102922978',
    projectId: 'anix-6434f',
    storageBucket: 'anix-6434f.firebasestorage.app',
    iosBundleId: 'com.anix.anix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXe-JijRZqO0GDidh3zCiwUnx9M9W5WDk',
    appId: '1:624102922978:web:73f4f85f6bece00c55dcbb',
    messagingSenderId: '624102922978',
    projectId: 'anix-6434f',
    authDomain: 'anix-6434f.firebaseapp.com',
    storageBucket: 'anix-6434f.firebasestorage.app',
    measurementId: 'G-K18RM5KH5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWoPFuMJgnsd7_kJLUT_8UQjdbIUPHvV4',
    appId: '1:624102922978:android:7e784141c9da038a55dcbb',
    messagingSenderId: '624102922978',
    projectId: 'anix-6434f',
    storageBucket: 'anix-6434f.firebasestorage.app',
  );

}